name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node/16
    steps:
      - uses: actions/checkout@v2
      - name: creates output
        run: npm ci && npm run build-prod
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'dist/colo-calc'
          destination-github-username: 'TheWWWorm'
          destination-repository-name: 'thewwworm.github.io'
          user-email: thewwworm@gmail.com
          target-branch: master